import"./CWj6FrbW.js";import"./yGgqKpKP.js";import{ae as A,ap as y,au as E,a as x,ah as I,ar as i,as as s,aq as L,at as S}from"./B_GMtRXg.js";import{s as j}from"./Hjms3FF-.js";import{c as H}from"./Ds-NI7hY.js";import{e as N}from"./0IlfFmyD.js";import{i as T}from"./Br1Wt3S0.js";import{p as m}from"./Ciidzp1H.js";import{o as z}from"./BjoOc52e.js";const c=`<!-- Cal element-click embed code begins -->
<script type="text/javascript">
  (function (C, A, L) { let p = function (a, ar) { a.q.push(ar); }; let d = C.document; C.Cal = C.Cal || function () { let cal = C.Cal; let ar = arguments; if (!cal.loaded) { cal.ns = {}; cal.q = cal.q || []; d.head.appendChild(d.createElement("script")).src = A; cal.loaded = true; } if (ar[0] === L) { const api = function () { p(api, arguments); }; const namespace = ar[1]; api.q = api.q || []; if(typeof namespace === "string"){cal.ns[namespace] = cal.ns[namespace] || api;p(cal.ns[namespace], ar);p(cal, ["initNamespace", namespace]);} else p(cal, ar); return;} p(cal, ar); }; })(window, "https://app.cal.com/embed/embed.js", "init");
Cal("init", "15min", {origin:"https://app.cal.com"});

  
  // Important: Please add the following attributes to the element that should trigger the calendar to open upon clicking.
  // \`data-cal-link="sudocker/15min"\`
  // data-cal-namespace="15min"
  // \`data-cal-config='{"layout":"month_view","useSlotsViewOnSmallScreen":"true"}'\`

  Cal.ns["15min"]("ui", {"hideEventTypeDetails":false,"layout":"month_view"});
  <\/script>
  <!-- Cal element-click embed code ends -->`;let w=!1;var D=y("<a> </a>");function F(o,a){A(a,!1);let e=m(a,"label",8,"Book a Fit Call"),n=m(a,"variant",8,"nav"),r=m(a,"fallbackHref",8,"mailto:hello@samagara.xyz");const d=c.match(/data-cal-link="([^"]+)"/),f=c.match(/data-cal-namespace="([^"]+)"/),u=c.match(/data-cal-config='([^']+)'/),v=d?d[1]:"",h=f?f[1]:"",g=u?u[1]:"",l=!!(v&&h&&g),q=l?{"data-cal-link":v,"data-cal-namespace":h,"data-cal-config":g}:{};function B(C){l&&C.preventDefault()}z(()=>{if(!l||w)return;[...c.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].forEach(M=>{const b=(M[1]||"").trim();if(!b)return;const p=document.createElement("script");p.type="text/javascript",p.text=b,document.body.appendChild(p)}),w=!0}),T();var t=D();let k;var _=i(t,!0);s(t),E(()=>{k=H(t,k,{href:l?"#":r(),class:`book-call-button ${n()}`,...q},"svelte-s9iloy"),j(_,e())}),N("click",t,B),x(o,t),I()}var O=y(`<section class="contact-section svelte-faov46"><div class="content svelte-faov46"><h3 class="svelte-faov46">Building something real?</h3> <p class="svelte-faov46">If you're validating a product or bringing AI into real workflows, let's talk. We'll tell you
      quickly if we're the right fit.</p> <div class="actions svelte-faov46"><!> <a href="https://www.linkedin.com/in/sudocker/" target="_blank" rel="noopener noreferrer" class="linkedin-button svelte-faov46">Connect on LinkedIn</a></div></div></section>`);function X(o){var a=O(),e=i(a),n=L(i(e),4),r=i(n);F(r,{variant:"solid",label:"Book a 15-min fit call"}),S(2),s(n),s(e),s(a),x(o,a)}export{F as B,X as C};
