import"./CWj6FrbW.js";import"./Cr1QaZZ0.js";import{a4 as M,af as y,al as j,ag as x,a7 as A,ai as i,aj as s,ah as E,ak as I}from"./CNydOz30.js";import{s as S}from"./BzFVD0bZ.js";import{c as T}from"./C8wrggly.js";import{e as H}from"./1qCSL4tI.js";import{i as N}from"./_uus0BoM.js";import{p as m}from"./BYFKmv8G.js";import{o as z}from"./B9hz3j3d.js";const X=""+new URL("../assets/samagra.Bsj6nRfT.png",import.meta.url).href,c=`<!-- Cal element-click embed code begins -->
<script type="text/javascript">
  (function (C, A, L) { let p = function (a, ar) { a.q.push(ar); }; let d = C.document; C.Cal = C.Cal || function () { let cal = C.Cal; let ar = arguments; if (!cal.loaded) { cal.ns = {}; cal.q = cal.q || []; d.head.appendChild(d.createElement("script")).src = A; cal.loaded = true; } if (ar[0] === L) { const api = function () { p(api, arguments); }; const namespace = ar[1]; api.q = api.q || []; if(typeof namespace === "string"){cal.ns[namespace] = cal.ns[namespace] || api;p(cal.ns[namespace], ar);p(cal, ["initNamespace", namespace]);} else p(cal, ar); return;} p(cal, ar); }; })(window, "https://app.cal.com/embed/embed.js", "init");
Cal("init", "15min", {origin:"https://app.cal.com"});

  
  // Important: Please add the following attributes to the element that should trigger the calendar to open upon clicking.
  // \`data-cal-link="sudocker/15min"\`
  // data-cal-namespace="15min"
  // \`data-cal-config='{"layout":"month_view","useSlotsViewOnSmallScreen":"true"}'\`

  Cal.ns["15min"]("ui", {"hideEventTypeDetails":false,"layout":"month_view"});
  <\/script>
  <!-- Cal element-click embed code ends -->`;let w=!1;var D=y("<a> </a>");function R(o,a){M(a,!1);let e=m(a,"label",8,"Book a Fit Call"),n=m(a,"variant",8,"nav"),r=m(a,"fallbackHref",8,"mailto:hello@samagara.xyz");const d=c.match(/data-cal-link="([^"]+)"/),f=c.match(/data-cal-namespace="([^"]+)"/),u=c.match(/data-cal-config='([^']+)'/),h=d?d[1]:"",v=f?f[1]:"",g=u?u[1]:"",l=!!(h&&v&&g),B=l?{"data-cal-link":h,"data-cal-namespace":v,"data-cal-config":g}:{};function L(C){l&&C.preventDefault()}z(()=>{if(!l||w)return;[...c.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].forEach(q=>{const b=(q[1]||"").trim();if(!b)return;const p=document.createElement("script");p.type="text/javascript",p.text=b,document.body.appendChild(p)}),w=!0}),N();var t=D();let k;var _=i(t,!0);s(t),j(()=>{k=T(t,k,{href:l?"#":r(),class:`book-call-button ${n()}`,...B},"svelte-s9iloy"),S(_,e())}),H("click",t,L),x(o,t),A()}var U=y(`<section class="contact-section svelte-faov46"><div class="content svelte-faov46"><h3 class="svelte-faov46">Building something real?</h3> <p class="svelte-faov46">If you're validating a product or bringing AI into real workflows, let's talk. We'll tell you
      quickly if we're the right fit.</p> <div class="actions svelte-faov46"><!> <a href="https://www.linkedin.com/in/sudocker/" target="_blank" rel="noopener noreferrer" class="linkedin-button svelte-faov46">Connect on LinkedIn</a></div></div></section>`);function Y(o){var a=U(),e=i(a),n=E(i(e),4),r=i(n);R(r,{variant:"solid",label:"Book a 15-min fit call"}),I(2),s(n),s(e),s(a),x(o,a)}export{R as B,Y as C,X as s};
